import { CompletionItem, CompletionItemKind } from 'vscode';
import { VmtSchema } from './vmt-document.js';

export const ShaderPriority: Record<string, number> = {
	vertexlitgeneric: 0,
	lightmappedgeneric: 0,
	unlitgeneric: 0,
	pbr: 0,
	sprite: 0,
	refract: 0,
	worldvertextransition: 0,
	water: 0,
	screenspace_general: 1,
	modulate: 1,
}

export const ShaderNames: Record<string, string> = {
	aftershock: 'Aftershock',
	black: 'Black',
	bloom: 'Bloom',
	core: 'Core',
	decalmodulate: 'DecalModulate',
	depthoffield: 'DepthOfField',
	depthwrite: 'DepthWrite',
	eyeglint: 'EyeGlint',
	eyerefract: 'EyeRefract',
	eyes: 'Eyes',
	introscreenspaceeffect: 'IntroScreenSpaceEffect',
	lightmapped_4wayblend: 'Lightmapped_4WayBlend',
	lightmappedgeneric: 'LightmappedGeneric',
	lightmappedreflective: 'LightmappedReflective',
	modulate: 'Modulate',
	monitorscreen: 'MonitorScreen',
	morphaccumulate: 'MorphAccumulate',
	morphweight: 'MorphWeight',
	motionblur: 'MotionBlur',
	paintblob: 'PaintBlob',
	pbr: 'PBR',
	portal: 'Portal',
	portalrefract: 'PortalRefract',
	portalstaticoverlay: 'PortalStaticOverlay',
	refract: 'Refract',
	screenspace_general: 'Screenspace_General',
	shadow: 'Shadow',
	shadowbuild: 'ShadowBuild',
	shadowmodel: 'ShadowModel',
	shatteredglass: 'ShatteredGlass',
	showz: 'ShowZ',
	sky_hdr: 'Sky_HDR',
	sky_sdr: 'Sky_SDR',
	solidenergy: 'SolidEnergy',
	splinerope: 'SplineRope',
	sprite: 'Sprite',
	spritecard: 'Spritecard',
	teeth: 'Teeth',
	unlitgeneric: 'UnlitGeneric',
	unlittwotexture: 'UnlitTwoTexture',
	vertexlitgeneric: 'VertexLitGeneric',
	videosurface: 'VideoSurface',
	volumeclouds: 'VolumeClouds',
	water: 'Water',
	windowimposter: 'WindowImposter',
	wireframe: 'Wireframe',
	worldimposter: 'WorldImposter',
	worldtwotextureblend: 'WorldTwoTextureBlend',
	worldvertextransition: 'WorldVertexTransition',
	writestencil: 'WriteStencil',
	writez: 'WriteZ',
};

export const CompilerParamSchema: VmtSchema = {
	'%tooltexture': { type: 'texture', help: 'The texture to show in the material browser. Unused in H++ and Strata Hammer.' },
	'%keywords': { type: 'string', help: 'A comma-separated list of keywords for the material browser.' },
	'%noportal': { type: 'bool', help: 'Prevents portals from being placed on this material.' },
	'%CompileBlockLOS': { type: 'bool' },
	'%CompileClip': { type: 'bool' },
	'%CompileDetail': { type: 'bool' },
	'%CompileLadder': { type: 'bool' },
	'%CompileNoDraw': { type: 'bool' },
	'%CompileNoLight': { type: 'bool' },
	'%CompileNonSolid': { type: 'bool' },
	'%CompileNPCClip': { type: 'bool' },
	'%CompilePassBullets': { type: 'bool' },
	'%CompileSkip': { type: 'bool' },
	'%CompileSlime': { type: 'bool' },
	'%CompileTeam': { type: 'bool' },
	'%CompileTrigger': { type: 'bool' },
	'%CompileWater': { type: 'bool' },
	'%PlayerClip': { type: 'bool' },
};

export const BuiltinTextures: CompletionItem[] = [
	'_rt_PowerOfTwoFB',
	'_rt_Fullscreen',
	'_rt_Camera',
	'_rt_FullFrameDepth',
	'_rt_FullFrameFB',
	'_rt_WaterReflection',
	'_rt_WaterRefraction',
	'_rt_SmallHDR0',
	'_rt_SmallHDR1',
	'_rt_SmallFB0',
	'_rt_SmallFB1',
	'_rt_TeenyFB%d',
	'env_cubemap'
].map<CompletionItem>(label => ({ label, kind: CompletionItemKind.Variable, sortText: '\xff' + label }));
